project_id = "msgiernjqizruvrfkqwe"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-casting]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.signup-request]
    verify_jwt = false
