-- Add new columns to profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS phone_prefix text,
ADD COLUMN IF NOT EXISTS phone_number text,
ADD COLUMN IF NOT EXISTS whatsapp_prefix text,
ADD COLUMN IF NOT EXISTS whatsapp_number text,
ADD COLUMN IF NOT EXISTS nationality text,
ADD COLUMN IF NOT EXISTS postal_code text,
ADD COLUMN IF NOT EXISTS residence_address jsonb,
ADD COLUMN IF NOT EXISTS domicile_address jsonb,
ADD COLUMN IF NOT EXISTS fiscal_code text,
ADD COLUMN IF NOT EXISTS work_cities text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS id_document_url text,
ADD COLUMN IF NOT EXISTS has_passport boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS passport_expiry date,
ADD COLUMN IF NOT EXISTS social_links jsonb,
ADD COLUMN IF NOT EXISTS website_url text,
ADD COLUMN IF NOT EXISTS has_minor_children boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS main_occupation text,
ADD COLUMN IF NOT EXISTS driving_licenses text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS travel_availability jsonb,
ADD COLUMN IF NOT EXISTS visas jsonb,
ADD COLUMN IF NOT EXISTS has_vat_number boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS vat_number text,
ADD COLUMN IF NOT EXISTS representation_type text;

-- Add new columns to talent_attributes table
ALTER TABLE public.talent_attributes
ADD COLUMN IF NOT EXISTS jacket_size text,
ADD COLUMN IF NOT EXISTS pants_size text,
ADD COLUMN IF NOT EXISTS chest integer,
ADD COLUMN IF NOT EXISTS waist integer,
ADD COLUMN IF NOT EXISTS hips integer,
ADD COLUMN IF NOT EXISTS shoulder_width integer,
ADD COLUMN IF NOT EXISTS neck_size integer,
ADD COLUMN IF NOT EXISTS shoe_size text,
ADD COLUMN IF NOT EXISTS underwear_sizes jsonb,
ADD COLUMN IF NOT EXISTS hair_length text,
ADD COLUMN IF NOT EXISTS hair_type text,
ADD COLUMN IF NOT EXISTS has_freckles boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS has_diastema boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS has_piercings boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS has_tattoos boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS abilities text[] DEFAULT '{}';